name: AssetStudioBuild

on:
  workflow_dispatch:
    inputs:
      target_framework:
        description: '选择编译目标 .NET 平台'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - net472
          - net8.0-windows
          - net9.0-windows

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ github.event.inputs.target_framework == 'all' && fromJSON('["net472", "net8.0-windows", "net9.0-windows"]') || fromJSON(format('["{0}"]', github.event.inputs.target_framework)) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Download FBX SDK
        run: |
          md fbx
          cd fbx
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_win.exe" -OutFile "fbxsdk.exe"
          Start-Process -FilePath "fbxsdk.exe" /S -Wait
          cd ..

      - name: Nuget Restore
        run: nuget restore

      - name: Build Solution (Native Dependencies)
        run: msbuild /p:Configuration=Release /p:TargetFramework=net472 /verbosity:minimal

      - name: Publish AssetStudioGUI for ${{ matrix.target }}
        if: matrix.target != 'net472'
        run: msbuild AssetStudioGUI/AssetStudioGUI.csproj /t:publish /p:Configuration=Release /p:TargetFramework=${{ matrix.target }} /p:SelfContained=false "/p:SolutionDir=${{ github.workspace }}\" /verbosity:minimal

      - name: Upload ${{ matrix.target }} Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AssetStudio.${{ matrix.target }}
          path: ${{ matrix.target != 'net472' && format('AssetStudioGUI/bin/Release/{0}/publish', matrix.target) || format('AssetStudioGUI/bin/Release/{0}', matrix.target) }}
